[package]
name = "arch-beezity-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.1"
anyhow = "1.0.75"
tokio = { version = "1.36.0", features = ["full"] }
dialoguer = "0.11.0"
indicatif = "0.17.8"
colored = "2.1.0" 